apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: krunalbhoyar/spring-petclinic-angular:tagVersion
        ports:
        - containerPort: 8085
        
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: angular-svc
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
